//! Index and specification types for tensor contractions.
//!
//! These types describe *what* to contract (which tensors, which indices)
//! without touching any tensor data. They are consumed by `PathOptimizer`
//! and `ContractionExecutor`.

use std::sync::atomic::{AtomicU32, Ordering};

use hashbrown::HashMap;
use smallvec::SmallVec;

use crate::error::{ContractionError, ContractResult};

// ---------------------------------------------------------------------------
// IndexId
// ---------------------------------------------------------------------------

/// Unique identifier for a tensor index (leg).
///
/// Wraps a `u32` for compact storage. Generated by `IndexId::new_unique()`
/// or constructed from a known value via `IndexId::from_raw()`.
///
/// In a `ContractionSpec`, an `IndexId` appearing on exactly two tensors
/// denotes a contracted (summed) index; one appearing on exactly one tensor
/// is a free index that appears in the output.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct IndexId(u32);

/// Global atomic counter for unique `IndexId` generation.
static NEXT_INDEX_ID: AtomicU32 = AtomicU32::new(0);

impl IndexId {
    /// Allocate a globally unique `IndexId` using an atomic counter.
    /// Thread-safe; intended for use at test setup or DSL initialization.
    pub fn new_unique() -> Self {
        IndexId(NEXT_INDEX_ID.fetch_add(1, Ordering::Relaxed))
    }

    /// Create from a known `u32` (for deserialization or snapshot tests).
    pub const fn from_raw(id: u32) -> Self {
        IndexId(id)
    }

    /// Extract the inner `u32`.
    pub fn raw(self) -> u32 {
        self.0
    }
}

impl std::fmt::Debug for IndexId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Idx({})", self.0)
    }
}

// ---------------------------------------------------------------------------
// TensorId
// ---------------------------------------------------------------------------

/// Unique identifier for a tensor within a contraction.
///
/// Wraps a `u32`. Assigned by the calling code (e.g., `tk-dmrg` assigns
/// site-tensor IDs from site indices).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TensorId(u32);

impl TensorId {
    pub const fn new(id: u32) -> Self {
        TensorId(id)
    }

    pub fn raw(self) -> u32 {
        self.0
    }
}

impl std::fmt::Debug for TensorId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "T({})", self.0)
    }
}

// ---------------------------------------------------------------------------
// IndexSpec
// ---------------------------------------------------------------------------

/// Dimension and layout metadata for one tensor leg.
///
/// Carries enough information for the optimizer to estimate FLOP counts
/// and memory costs without accessing actual tensor data.
#[derive(Clone, Debug)]
pub struct IndexSpec {
    /// Logical dimension of this leg.
    pub dim: usize,
    /// Whether this leg is contiguous (unit stride) in the current layout.
    /// Used by the cost estimator to determine whether a transpose is needed.
    pub is_contiguous: bool,
}

// ---------------------------------------------------------------------------
// ContractionSpec
// ---------------------------------------------------------------------------

/// A contracted index: shared `IndexId` with locations on two tensors.
#[derive(Clone, Debug)]
pub struct ContractedPair {
    pub index: IndexId,
    pub tensor_a: TensorId,
    pub leg_a: usize,
    pub tensor_b: TensorId,
    pub leg_b: usize,
}

/// A free index: `IndexId` appearing on exactly one tensor.
#[derive(Clone, Debug)]
pub struct FreeIndex {
    pub index: IndexId,
    pub tensor: TensorId,
    pub leg: usize,
}

/// Complete specification of a multi-tensor contraction.
///
/// Represents the expression:
///   Result_{free_indices} = Σ_{contracted_indices} T₁ ⊗ T₂ ⊗ ... ⊗ Tₙ
///
/// Index pairing: an `IndexId` that appears on exactly two tensors is
/// contracted (summed). An `IndexId` that appears on exactly one tensor
/// is a free index and appears in the output.
#[derive(Clone, Debug)]
pub struct ContractionSpec {
    /// One entry per input tensor: (TensorId, ordered legs).
    pub tensors: Vec<(TensorId, Vec<IndexId>)>,
    /// Ordered free indices of the output tensor.
    pub output_indices: Vec<IndexId>,
    /// Pre-computed contracted pairs (cached for optimizer performance).
    contracted_pairs: Vec<ContractedPair>,
    /// Pre-computed free indices (cached for optimizer performance).
    free_indices: Vec<FreeIndex>,
}

impl ContractionSpec {
    /// Construct and validate the specification.
    ///
    /// # Errors
    /// - `IndexAppearsTooManyTimes` if any `IndexId` appears on more than two tensors.
    /// - `DuplicateIndexOnTensor` if any tensor has two legs with the same `IndexId`.
    /// - `OutputIndexNotFree` if `output_indices` contains a contracted index.
    /// - `EmptySpec` if no tensors are provided.
    pub fn new(
        tensors: Vec<(TensorId, Vec<IndexId>)>,
        output_indices: Vec<IndexId>,
    ) -> ContractResult<Self> {
        if tensors.is_empty() {
            return Err(ContractionError::EmptySpec);
        }

        // Check for duplicate indices on the same tensor.
        for (tid, legs) in &tensors {
            for (i, idx_i) in legs.iter().enumerate() {
                for (j, idx_j) in legs.iter().enumerate().skip(i + 1) {
                    if idx_i == idx_j {
                        return Err(ContractionError::DuplicateIndexOnTensor {
                            tensor: *tid,
                            index: *idx_i,
                            leg_a: i,
                            leg_b: j,
                        });
                    }
                }
            }
        }

        // Count how many tensors each IndexId appears on.
        let mut index_locations: HashMap<IndexId, SmallVec<[(TensorId, usize); 2]>> =
            HashMap::new();
        for (tid, legs) in &tensors {
            for (leg_pos, idx) in legs.iter().enumerate() {
                index_locations
                    .entry(*idx)
                    .or_default()
                    .push((*tid, leg_pos));
            }
        }

        // Validate: no index appears on more than 2 tensors.
        for (idx, locs) in &index_locations {
            if locs.len() > 2 {
                return Err(ContractionError::IndexAppearsTooManyTimes {
                    index: *idx,
                    count: locs.len(),
                });
            }
        }

        // Build contracted pairs and free indices.
        let mut contracted_pairs = Vec::new();
        let mut free_indices = Vec::new();

        for (idx, locs) in &index_locations {
            if locs.len() == 2 {
                contracted_pairs.push(ContractedPair {
                    index: *idx,
                    tensor_a: locs[0].0,
                    leg_a: locs[0].1,
                    tensor_b: locs[1].0,
                    leg_b: locs[1].1,
                });
            } else {
                free_indices.push(FreeIndex {
                    index: *idx,
                    tensor: locs[0].0,
                    leg: locs[0].1,
                });
            }
        }

        // Validate output_indices: must all be free indices.
        let contracted_set: hashbrown::HashSet<IndexId> =
            contracted_pairs.iter().map(|p| p.index).collect();
        for idx in &output_indices {
            if contracted_set.contains(idx) {
                return Err(ContractionError::OutputIndexNotFree { index: *idx });
            }
        }

        Ok(ContractionSpec {
            tensors,
            output_indices,
            contracted_pairs,
            free_indices,
        })
    }

    /// Number of input tensors.
    pub fn n_tensors(&self) -> usize {
        self.tensors.len()
    }

    /// Contracted index pairs (cached at construction time).
    pub fn contracted_pairs(&self) -> &[ContractedPair] {
        &self.contracted_pairs
    }

    /// Free indices (cached at construction time).
    pub fn free_indices(&self) -> &[FreeIndex] {
        &self.free_indices
    }

    /// Find all indices shared between two tensors in this spec.
    pub fn shared_indices(&self, a: TensorId, b: TensorId) -> Vec<&ContractedPair> {
        self.contracted_pairs
            .iter()
            .filter(|p| {
                (p.tensor_a == a && p.tensor_b == b)
                    || (p.tensor_a == b && p.tensor_b == a)
            })
            .collect()
    }

    /// Validate that all contracted index pairs have matching dimensions.
    ///
    /// This is a defense-in-depth check: the `IndexMap` must already be populated
    /// with dimension info for all tensors before calling this. Typically invoked
    /// by the optimizer or executor before starting work.
    ///
    /// # Errors
    /// Returns `ContractionError::DimensionMismatch` if any contracted pair
    /// has different dimensions on the two tensors it connects.
    pub fn validate_dimensions(&self, index_map: &IndexMap) -> ContractResult<()> {
        for pair in &self.contracted_pairs {
            let dim_a = index_map.dim(pair.tensor_a, pair.leg_a);
            let dim_b = index_map.dim(pair.tensor_b, pair.leg_b);
            if let (Some(da), Some(db)) = (dim_a, dim_b) {
                if da != db {
                    return Err(ContractionError::DimensionMismatch {
                        index: pair.index,
                        tensor_a: pair.tensor_a,
                        leg_a: pair.leg_a,
                        dim_a: da,
                        tensor_b: pair.tensor_b,
                        leg_b: pair.leg_b,
                        dim_b: db,
                    });
                }
            }
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// IndexMap
// ---------------------------------------------------------------------------

/// Maps each `(TensorId, leg_position)` pair to its `IndexSpec`.
///
/// Passed to `PathOptimizer::optimize` to enable cost estimation without
/// access to tensor data.
#[derive(Clone, Debug)]
pub struct IndexMap {
    specs: HashMap<(TensorId, usize), IndexSpec>,
}

impl IndexMap {
    pub fn new() -> Self {
        IndexMap {
            specs: HashMap::new(),
        }
    }

    /// Register the leg specifications for one tensor.
    pub fn insert(&mut self, tensor_id: TensorId, specs: Vec<IndexSpec>) {
        for (leg, spec) in specs.into_iter().enumerate() {
            self.specs.insert((tensor_id, leg), spec);
        }
    }

    /// Look up the `IndexSpec` for one leg.
    pub fn get(&self, tensor_id: TensorId, leg: usize) -> Option<&IndexSpec> {
        self.specs.get(&(tensor_id, leg))
    }

    /// Get the dimension of a specific leg.
    pub fn dim(&self, tensor_id: TensorId, leg: usize) -> Option<usize> {
        self.get(tensor_id, leg).map(|s| s.dim)
    }

    /// Compare dimensions only (not strides) to determine if a plan is still valid.
    pub fn dims_match(&self, other: &IndexMap) -> bool {
        if self.specs.len() != other.specs.len() {
            return false;
        }
        self.specs.iter().all(|(key, spec)| {
            other.specs.get(key).map_or(false, |other_spec| {
                spec.dim == other_spec.dim
            })
        })
    }
}

impl Default for IndexMap {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn index_id_unique() {
        let a = IndexId::new_unique();
        let b = IndexId::new_unique();
        assert_ne!(a, b);
    }

    #[test]
    fn index_id_from_raw() {
        let a = IndexId::from_raw(42);
        assert_eq!(a.raw(), 42);
    }

    #[test]
    fn spec_new_valid_two_tensor() {
        let i = IndexId::from_raw(100);
        let j = IndexId::from_raw(101);
        let k = IndexId::from_raw(102);

        // A(i, j) * B(j, k) → C(i, k)
        let spec = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i, j]),
                (TensorId::new(1), vec![j, k]),
            ],
            vec![i, k],
        )
        .unwrap();

        assert_eq!(spec.n_tensors(), 2);
        assert_eq!(spec.contracted_pairs().len(), 1);
        assert_eq!(spec.contracted_pairs()[0].index, j);
        assert_eq!(spec.free_indices().len(), 2);
    }

    #[test]
    fn spec_new_index_too_many_times() {
        let i = IndexId::from_raw(200);
        let result = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i]),
                (TensorId::new(1), vec![i]),
                (TensorId::new(2), vec![i]),
            ],
            vec![],
        );
        assert!(matches!(
            result,
            Err(ContractionError::IndexAppearsTooManyTimes { count: 3, .. })
        ));
    }

    #[test]
    fn spec_new_duplicate_on_tensor() {
        let i = IndexId::from_raw(300);
        let result = ContractionSpec::new(
            vec![(TensorId::new(0), vec![i, i])],
            vec![],
        );
        assert!(matches!(
            result,
            Err(ContractionError::DuplicateIndexOnTensor { leg_a: 0, leg_b: 1, .. })
        ));
    }

    #[test]
    fn spec_new_output_index_not_free() {
        let i = IndexId::from_raw(400);
        let j = IndexId::from_raw(401);
        let result = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i]),
                (TensorId::new(1), vec![i]),
            ],
            vec![i], // i is contracted, not free
        );
        assert!(matches!(
            result,
            Err(ContractionError::OutputIndexNotFree { .. })
        ));
    }

    #[test]
    fn spec_shared_indices_two_tensors() {
        let i = IndexId::from_raw(450);
        let j = IndexId::from_raw(451);
        let k = IndexId::from_raw(452);

        let spec = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i, j]),
                (TensorId::new(1), vec![j, k]),
            ],
            vec![i, k],
        )
        .unwrap();

        let shared = spec.shared_indices(TensorId::new(0), TensorId::new(1));
        assert_eq!(shared.len(), 1);
        assert_eq!(shared[0].index, j);
    }

    #[test]
    fn spec_shared_indices_disjoint() {
        let i = IndexId::from_raw(460);
        let j = IndexId::from_raw(461);
        let k = IndexId::from_raw(462);
        let l = IndexId::from_raw(463);

        let spec = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i, j]),
                (TensorId::new(1), vec![k, l]),
            ],
            vec![i, j, k, l],
        )
        .unwrap();

        let shared = spec.shared_indices(TensorId::new(0), TensorId::new(1));
        assert!(shared.is_empty());
    }

    #[test]
    fn spec_dimension_mismatch_detected() {
        let i = IndexId::from_raw(470);
        let j = IndexId::from_raw(471);

        let spec = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i, j]),
                (TensorId::new(1), vec![j]),
            ],
            vec![i],
        )
        .unwrap();

        let mut index_map = IndexMap::new();
        index_map.insert(
            TensorId::new(0),
            vec![
                IndexSpec { dim: 4, is_contiguous: true },
                IndexSpec { dim: 3, is_contiguous: true }, // j has dim 3 on tensor 0
            ],
        );
        index_map.insert(
            TensorId::new(1),
            vec![
                IndexSpec { dim: 5, is_contiguous: true }, // j has dim 5 on tensor 1 — mismatch!
            ],
        );

        let result = spec.validate_dimensions(&index_map);
        assert!(matches!(
            result,
            Err(ContractionError::DimensionMismatch { dim_a: 3, dim_b: 5, .. })
        ));
    }

    #[test]
    fn spec_dimension_match_passes() {
        let i = IndexId::from_raw(480);
        let j = IndexId::from_raw(481);

        let spec = ContractionSpec::new(
            vec![
                (TensorId::new(0), vec![i, j]),
                (TensorId::new(1), vec![j]),
            ],
            vec![i],
        )
        .unwrap();

        let mut index_map = IndexMap::new();
        index_map.insert(
            TensorId::new(0),
            vec![
                IndexSpec { dim: 4, is_contiguous: true },
                IndexSpec { dim: 3, is_contiguous: true },
            ],
        );
        index_map.insert(
            TensorId::new(1),
            vec![
                IndexSpec { dim: 3, is_contiguous: true },
            ],
        );

        assert!(spec.validate_dimensions(&index_map).is_ok());
    }

    #[test]
    fn index_map_dims_match() {
        let mut a = IndexMap::new();
        a.insert(TensorId::new(0), vec![IndexSpec { dim: 3, is_contiguous: true }]);

        let mut b = IndexMap::new();
        b.insert(TensorId::new(0), vec![IndexSpec { dim: 3, is_contiguous: false }]);

        // Strides differ but dims match => true
        assert!(a.dims_match(&b));

        let mut c = IndexMap::new();
        c.insert(TensorId::new(0), vec![IndexSpec { dim: 5, is_contiguous: true }]);

        // Dims differ => false
        assert!(!a.dims_match(&c));
    }
}
